### ISSUE TITLE
Fix the Asynchronous calls problem

### ISSUE THREAD

**Issue by rgoraya** [rgoraya/wc_master#1]
While accepting suggestions, sometimes the MediaWiki API takes more time to provide the Wikipedia Description and the Image and the accept form is submitted with Empty values - and therefore the suggestion is not accepted. Presently we are dealing with this problem by asking users to wait for a second or two before clicking the accept button after hovering the mouse onto the accept button (and let the system pull required data from MediaWiki API in the meantime)

**Comment by dLobatog** [comment]
Could you point out the sections of the code that may be involved on this? Thanks for noticing the bug, I was trying to add some issues and had this very same problem but had no idea about what was the problem.

From what I've read it looks like get_suggestions in suggestions.rb model is the main responsible, and maybe we can do something with create in suggestions controller but so far I don't have it very clear. Also get_wiki_description in issue model plays an important role here.

Question,  once the Issue is retrieved with this_issue = Issue.find(issueid)  , is there any way to check if that issue has already been created or not? My point is that we're using collect on causes,effects, etc... regardless if the issue exist or not which takes up precious time in case it doesn't previously exist because nothing is going to be returned. 

If the API is that slow could the best solution be not to allow the user to click until it's ready? I'm going to work in clarifying suggestions model and maybe we can discuss this in person this week?

**Comment by rgoraya** [comment]
Hi Daniel,

thanks for the note.

While improving the suggestions model is still important, we might be doing
away with the API call getting the suggestion content.

The approach that you suggested (waiting for the API to get data before
user is allowed to accept it) is what I too thought as a potential solution
but with the new requirements in mind we might not be needing to do that.

Look forward to talking more about the model and about the suggestion
retrieval though.

Raminder

2012/1/9 Daniel Lobato Garca <
reply@reply.github.com

> Could you point out the sections of the code that may be involved on this?
> Thanks for noticing the bug, I was trying to add some issues and had this
> very same problem but had no idea about what was the problem.
> 
> From what I've read it looks like get_suggestions in suggestions.rb model
> is the main responsible, and maybe we can do something with create in
> suggestions controller but so far I don't have it very clear.
> 
> If the API is that slow could the best solution be not to allow the user
> to click until it's ready? I'm going to work in clarifying suggestions
> model and maybe we can discuss this in person this week?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rgoraya/wc_master/issues/1#issuecomment-3424817

## 

Sincere Thanks!

Goraya Raminder Singh
Bren School of Information and Computer Sciences
University of California, Irvine
Irvine, CA 92697-3425rgoraya@uci.edu
