### ISSUE TITLE
URL Listed as a Title

### ISSUE THREAD

**Issue by DinorahCr** [rgoraya/wc_master#17]
When going through suggestions on subsets and supersets for deforestation an auto generated suggestion had a url listed as its title.

**Comment by dLobatog** [comment]
Weird... I rejected it but it was something of the type "//wikitionary.org ..." . If you find any other suggestion like that comment in this thread.

**Comment by duyetln** [comment]
It is because the system assumes that most URLs within any paragraph of any article have the form href="/wiki/article_name". Base on this assumption, most of the retrieved name for the suggestions will be correct. However, once in a while, some URL is exceptional, which makes the parsing fails and produces weird titles like the one above.

**Comment by duyetln** [comment]
I also tweaked the code a little bit to improve the chance of getting the "right" title.
